### ISSUE TITLE
ImportError: No module named 'typo_tables'

### ISSUE THREAD

**Issue by imrek** [richmilne/JaroWinkler#1]
I've installed with `sudo pip3 install jaro_winkler` and when I try `import jaro`, I get an `ImportError` for `typo_tables`. I haven't dived into the source code yet, what is the quickest workaround for this error?

```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jaro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/jaro/__init__.py", line 36, in <module>
    import typo_tables
ImportError: No module named 'typo_tables'

```

**Comment by richmilne** [comment]
Quickest work-around is to install and run package under Python2... as I haven't got round to porting the code to Python v3 yet! I've started porting now - will update you on the progress, but won't be able to do much this weekend, I'm afraid.
